spring.application.name=copaia

spring.datasource.url=jdbc:postgresql://localhost:5432/copaia
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

gemini.api.key=${GEMINI_API_KEY:}
gemini.api.model=gemini-2.0-flash
gemini.api.base-url=https://generativelanguage.googleapis.com/v1beta/models

football.api.key=${FOOTBALL_API_KEY:}
football.api.url=https://api.football-data.org/v4
